"""fix_intakes_dish_id_comment

Revision ID: e44dc97dd68c
Revises: 16d48fc59bff
Create Date: 2025-07-26 23:34:27.263023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e44dc97dd68c'
down_revision = '16d48fc59bff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('intakes', 'dish_id',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='Foreign key to dishes table. Can be NULL for water-only intakes.',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('intakes', 'dish_id',
               existing_type=sa.BIGINT(),
               comment='Foreign key to dishes table. Can be NULL for water-only intakes.',
               existing_nullable=True)
    # ### end Alembic commands ### 